services:
  jupyterhub:
    build: 
      context: ./jupyterhub
      dockerfile: Dockerfile
    image: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/data
      - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    networks:
      jupyterhub-network:
        aliases:
          - jupyterhub
    environment:
      - DOCKER_NETWORK_NAME=jupyterhub-network
      - JUPYTERHUB_API_TOKEN=super-secret  # Token pour le proxy HTTP
      - CONFIGPROXY_AUTH_TOKEN=super-secret  # Même token
    user: root
    container_name: jupyterhub
    restart: unless-stopped

  jupyter-lab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    image: jupyter-lab
    user: root  # Ajouter cette ligne
    networks:
      - jupyterhub-network
    volumes:
      - "jupyterhub-user-data:/home/jovyan/work"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=1000  # UID de l'utilisateur jovyan
      - NB_GID=100   # GID du groupe users
    deploy:
      replicas: 0
    container_name: jupyter-lab-template

volumes:
  jupyterhub_data:
    driver: local
  jupyterhub-user-data:
    driver: local

networks:
  jupyterhub-network:
    name: jupyterhub-network  # Force ce nom exact sans préfixe
    driver: bridge