apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-data
  namespace: jupyterhub
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath