apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jhub-pvc-manager
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","list","watch","create","delete","update","patch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get","list","watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jhub-pvc-manager-binding
subjects:
- kind: ServiceAccount
  name: jupyterhub
  namespace: jupyterhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jhub-pvc-manager